### ISSUE TITLE
Bintray / JCenter is deprecated

### ISSUE THREAD

**Issue by charleskorn** [araqnid/hamkrest-json#1]
Thanks for putting this library together. Given that [Bintray has shut down](https://jfrog.com/center-sunset/), do you have any plans to publish this library on Maven Central?

**Comment by araqnid** [comment]
Yes, absolutely. I've got a token enabled for it, I just need to get round to hooking it up to all the repos (and moving off Travis to Github actions, probably). Thanks for reminding me!

**Comment by araqnid** [comment]
I've released a 1.1.2 version to Maven Central, I think it's now just waiting for them to activate the sync (it's the first time I'm releasing something to the org.araqnid namespace), but it should be available soon.

**Comment by araqnid** [comment]
Looks like it's there: https://repo.maven.apache.org/maven2/org/araqnid/hamkrest/hamkrest-json/1.1.2/

**Comment by charleskorn** [comment]
In case anyone else comes across the same issue, the dependency coordinates are slightly different on Maven Central:

* Bintray: `org.araqnid:hamkrest-json:1.1.2`
* Maven Central: `org.araqnid.hamkrest:hamkrest-json:1.1.2`
